### ISSUE TITLE
Cannot import name export from notion2jekyll

### ISSUE THREAD

**Issue by yogeshvar** [echo724/notion2jekyll#1]
@echo724 Loved your work. Could you please check on this? 

![image](https://user-images.githubusercontent.com/17572818/87775927-7f761d80-c844-11ea-93fe-5824b9ea3a77.png)

Thanks in advance.

**Comment by echo724** [comment]
Hello!
Sorry for the misinstruction. I changed the function name after making the README. 
It is `export_out` instead of 'export'.
Thank you.

**Comment by yogeshvar** [comment]
@echo724 
Using the python3 in command-line, the following error occurs
```
Notion Page Url:
~Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mags/Library/Python/3.7/lib/python/site-packages/notion2jekyll/__main__.py", line 4, in <module>
    export_cli()
  File "/Users/mags/Library/Python/3.7/lib/python/site-packages/notion2jekyll/jekyll_exporter.py", line 60, in export_cli
    export(url,token_v2)
NameError: name 'export' is not defined
```

Using python-cli, I get the following error.
```
>>> from notion2jekyll import export_out
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'export_out' from 'notion2jekyll' (/Users/mags/Library/Python/3.7/lib/python/site-packages/notion2jekyll/__init__.py)
```

**Comment by echo724** [comment]
Hey I changed the way to use the package. Please check the README Thank you.

> Hey
> 
> Thank you for letting me know the error.
> 
> Can you reinstall the notion2jekyll? I fixed the error and updated the package. Thank you.
> 
> + Oh I made a mistake on Readme. 
> In python script, the command is `from notion2jekyll.jekyll_exporter import export_out`
