### ISSUE TITLE
Jekyll exporter looks for non-existing PageBlock attribute

### ISSUE THREAD

**Issue by villasv** [echo724/notion2jekyll#2]
```
$ pip list | grep notion
notion                             0.0.25
notion2jekyll                      0.1.5.3
notion2md                          0.1.7.5
```

```
$ python -m notion2jekyll
Traceback (most recent call last):
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/__main__.py", line 4, in <module>
    export_cli()
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/jekyll_exporter.py", line 60, in export_cli
    export_out(url,token_v2)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/jekyll_exporter.py", line 73, in export_out
    file,dir = make_file(page)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/jekyll_exporter.py", line 24, in make_file
    fname = set_filename(block)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/jekyll_exporter.py", line 15, in set_filename
    date = format_date(block)
  File "/home/villasv/.pyenv/versions/3.6.5/lib/python3.6/site-packages/notion2jekyll/jekyll_exporter.py", line 6, in format_date
    date = block.get_property("created")
AttributeError: 'PageBlock' object has no attribute 'get_property'
```

**Comment by villasv** [comment]
Maybe the docs should mention what page properties are required for the export to work? I could figure it out by trial and error, but would have been faster if it was documented.

**Comment by echo724** [comment]
Wow Thanks! 
I only tried the url that has properties.
I could't notice it without you.
I will fix it soon! Thank you for your interest.

I fixed it. Please update the package. Thanks
